config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :posts

  root 'posts#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'

end

app/models/Category.rb
class Category < ActiveRecord::Base
	has_many :connections
	has_many :posts, through: :connections
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :connections
	has_many :posts, through: :connections
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/connection.rb
class Connection < ActiveRecord::Base
	belongs_to :category
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :connections
	has_many :categories, through: :connections
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments

	validates :name, presence: true
	validates :name, length: { minimum: 2 }
  	validates :name, length: { maximum: 50 }
	validates :email, presence: true
	validates :email, uniqueness: true
	has_secure_password validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  
  def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/posts_controller.rb
class  PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post= Post.new
  end

  def create
    post = Post.new(post_params)

    if post.save!
      redirect_to posts_path
    else
      render :new
    end
  end

  def post_params
    params.require(:post).permit(:title, :content)
    binding.pry
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    #登入頁面使用
  end

  def create
    #尋找使用者
    user = User.find_by(name: params[:name])   
    #驗證使用者，若成功，就建立一個 session，把 user_id 放入 session hash
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    #登出畫面使用，刪除 session hash 裡面的 user_id
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/userss_controllers.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private 

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "PostBoard", root_path, :class => 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to 'New Post', new_post_path %></li>
        <% else %>
          <li><%= link_to 'Register', register_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <%= link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do %>
            <%= current_user.name %> <span class='caret'></span>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to 'User Profile', user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Logout', logout_path %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Guestbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation'%>
<div class="container">
	<div class="row">
		<div Class = "col-md-12">
			<%= yield %>
		</div>
	</div>
</div>
</body>
</html>

app/views/posts/index.html.erb
<%= render 'shared/title',title:'Post List'%>
<% @posts.each do |post|%>
	<div class="row">
	  <div class="well col-sm-4">
		  <p><%=post.title%></p>
		  <p><%= post.content %></p>
		  <%= link_to "show post", post_path(post)%>
	  </div>
	 </div>
<%end%>

app/views/posts/new.html.erb
<%= render 'shared/title',title: "New Post"%>

<div class="well col-md-12">
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <br>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <%= f.label :content %>
      <br>
      <%= f.text_area :content, rows: 5 %>
    </div>
  <br>
    <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
  <% end %>
</div>

<%= link_to 'Back to Post List', posts_path %>

app/views/posts/show.html.erb
<%= render 'shared/title',title:'Show Page'%>

<div>
<%=@post.title%>
</div>
<div>
<%=@post.content%>
</div>

<% @post.comments.each do |post|%>
  <div>
  <p><%= post.content %></p>
  </div>
<%end%>

<div></div>

  <%= link_to "back to list page", posts_path%>

app/views/shared/_title.html.erb
<h3><%=title%></h3>
<hr>

app/views/users/new.html.erb
<h4>Register</h4>

<div class="well col-md-6">
  <%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <br>
    <%= f.password_field :password%>
  </div>
  <br>
  <%= f.submit(@user.new_record? ? 'Register' : 'Update Profile', class: 'btn btn-success') %>
  <% end %>
</div>

實作使用者註冊功能

# config/routes.rb

resources :users, only: [:new, :create]

get '/register', to: 'users#new'

實作使用者註冊功能

# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  
  def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

實作使用者註冊功能 # app/views/users/new.html.erb <h4>Register</h4> <div class="well col-md-6"> <%= form_for @user do |f| %> <div class="form-group"> <%= f.label :name %> <br> <%= f.text_field :name %> </div> <div class="form-group"> <%= f.label :password %> <br> <%= f.password_field :password%> </div> <br> <%= f.submit(@user.new_record? ? 'Register' : 'Update Profile', class: 'btn btn-success') %> <% end %> </div>

Create a presentation like this